### ISSUE TITLE
MSSQL DB Cnnnector

### ISSUE THREAD

**Issue by Namec999** [NumbersStationAI/NSQL#7]
Hello, is there any chance you can add example with MS SQL support, it will help us a lot.

best

**Comment by senwu** [comment]
Hi @Namec999 ,

We appreciate your interest in our work. Currently, we have plans to include cloud database examples in future releases. However, if you are interested in contributing to our NSQL codebase, we would be delighted to have you as a contributor.

Additionally, we would like to provide you with some references that you may find helpful:

GCP Postgres: https://cloud.google.com/sql/docs/postgres/samples/cloud-sql-postgres-sqlalchemy-connect-connector
AWS Redshift: https://docs.aws.amazon.com/redshift/latest/mgmt/python-connect-examples.html
Azure database: https://learn.microsoft.com/en-us/azure/azure-sql/database/connect-query-python?view=azuresql
MS SQL: https://learn.microsoft.com/en-us/sql/connect/python/python-driver-for-sql-server?view=sql-server-ver16
